plugins { id 'dev.architectury.loom' }
base { archivesName = rootProject.archives_base_name }
dependencies {
    minecraft libs.minecraft
    mappings loom.officialMojangMappings()
    compileOnly libs.fabric.loader
    compileOnly libs.mixin
    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
}
tasks.named('jar', Jar) { archiveFileName = "${rootProject.archives_base_name}-${project.version}-common.jar" }
tasks.named('sourcesJar', Jar) { archiveFileName = "${rootProject.archives_base_name}-${project.version}-common-sources.jar" }
